steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['get', '-d']
  env: ['GOPATH=go']
  
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app','deploy', 'go/src/$PROJECT_ID']
  env: ['GOPATH=go']
  timeout: 300s
